"""Unit tests for the Kahf-seeded deterministic prime construction.

Locks the canonical encoding so any future change to the algorithm
breaks these tests loudly.

Run:
    python -m unittest test_determinism.py -v
"""

import hashlib
import unittest

from kahf_seeded_search import (
    KAHF_PRIMES,
    SEED_LABEL,
    DEFAULT_BITS,
    canonical_seed_input,
    master_seed,
    candidate,
    generator_on_curve,
)


# Frozen golden values for the BCS-521-V2 cipher suite.
# DO NOT change without bumping the seed schema label to v2.
# (V1 = the existing random-search BCS-521 prime in bcs-spec/bcs-521.md;
#  this file ONLY governs V2 and never touches V1.)
GOLDEN_CANONICAL = (
    b"BCS-521-V2-Seed-v1:"
    b"p_kahf_first_decimal=2141;"
    b"p_kahf_last_zf=2969;"
    b"p_kahf_sleepers=7;"
    b"p_kahf_surah_zf=19;"
    b"p_kahf_years_zf=373;"
    b"a2=-2;a4=5;a6=4;bits=521;"
)

GOLDEN_MASTER_SEED_HEX = (
    "a7e2095812a53b18111510409951b3472dcdbfdc49a08600dd83f3b644a8ebed"
    "dcd856198544a56d905272203057ee7b6c1a55b080fd8d51a9144b739ed95cbd"
)


class TestKahfSeededCanonical(unittest.TestCase):

    def test_canonical_input_frozen(self):
        self.assertEqual(canonical_seed_input(SEED_LABEL, DEFAULT_BITS),
                         GOLDEN_CANONICAL)

    def test_canonical_input_length(self):
        self.assertEqual(len(GOLDEN_CANONICAL), 147)

    def test_master_seed_frozen_hex(self):
        seed = master_seed(SEED_LABEL, DEFAULT_BITS)
        self.assertEqual(seed.hex(), GOLDEN_MASTER_SEED_HEX)
        self.assertEqual(len(seed), 64)

    def test_kahf_primes_alphabetical_order(self):
        keys = [k for k, _ in KAHF_PRIMES]
        self.assertEqual(keys, sorted(keys))
        self.assertEqual(len(KAHF_PRIMES), 5)


class TestKahfSeededCandidate(unittest.TestCase):

    def test_determinism(self):
        for c in [0, 1, 7, 100, 99999]:
            self.assertEqual(candidate(c), candidate(c))

    def test_bit_width_and_oddness(self):
        for c in range(100):
            p = candidate(c)
            self.assertEqual(p.bit_length(), DEFAULT_BITS,
                             msg=f"counter {c} produced bit_length={p.bit_length()}")
            self.assertEqual(p % 2, 1, msg=f"counter {c} produced even value")

    def test_label_sensitivity(self):
        a = candidate(0, label="BCS-521-V2-Seed-v1")
        b = candidate(0, label="BCS-521-V2-Seed-v2")
        self.assertNotEqual(a, b)

    def test_v1_label_distinct_from_v2_label(self):
        # If anyone ever ports the V1 (existing) prime origin to this format,
        # the seed streams must be disjoint by construction.
        v2 = candidate(0, label="BCS-521-V2-Seed-v1")
        v1_hypothetical = candidate(0, label="BCS-521-V1-Seed-v1")
        self.assertNotEqual(v2, v1_hypothetical)

    def test_bits_sensitivity(self):
        a = candidate(0, bits=512)
        b = candidate(0, bits=521)
        self.assertNotEqual(a, b)
        self.assertEqual(a.bit_length(), 512)
        self.assertEqual(b.bit_length(), 521)

    def test_counter_sensitivity(self):
        a = candidate(0)
        b = candidate(1)
        self.assertNotEqual(a, b)

    def test_negative_counter_rejected(self):
        with self.assertRaises(ValueError):
            candidate(-1)

    def test_first_three_candidates_frozen_hex(self):
        # These 32-hex-char prefixes were generated by this V2 implementation
        # (label = BCS-521-V2-Seed-v1). Any future Rust port must match.
        expected_prefixes = [
            "0x1b8ec6cb7c8819a2a74bb8f092f4ef96",
            "0x1a2365833e84694635fc5975a8893150",
            "0x192a5f1f9af87e2256108555f0b34ce5",
        ]
        for c, expected in enumerate(expected_prefixes):
            p = candidate(c)
            self.assertTrue(hex(p).startswith(expected),
                            msg=f"counter {c}: got {hex(p)[:34]}, want {expected}")


class TestGeneratorOnCurve(unittest.TestCase):

    def test_g_on_curve_for_assorted_primes(self):
        # G = (0, 2) satisfies y^2 = x^3 - 2x^2 + 5x + 4 ⇒ 4 ≡ 4 for any p > 4.
        for p in [17, 1009, 99991, candidate(0), candidate(1)]:
            self.assertTrue(generator_on_curve(p), msg=f"p={p}")


if __name__ == "__main__":
    unittest.main(verbosity=2)
