// BCS-521 frozen test vectors — integration tests
//
// Generated by BCS_521_FREEZE_TEST_VECTORS.py on 2026-05-16 (regenerated 2026-05-17
// with Kahf binding section). Every implementation MUST reproduce these exact outputs.
//
// All EC, HKDF, AES-GCM, and Kahf-bound values are FROZEN.
//
// Run:  cargo test --release --test test_vectors_521

use aes_gcm::{
    aead::{Aead, KeyInit, Payload},
    Aes256Gcm, Key, Nonce,
};
use num_bigint::BigUint;
use bcs_core_rust::{bcs521, hkdf_sha512_64, hkdf_sha512_64_kahf, kahf_domain_separator, Point};

// ---- confirmed AES-256-GCM values (Kaggle run 2026-05-16) ----
const AES_KEY_HEX:        &str = "fab1b43387c2bf7018d0a0c16d8ffb8d3713ac7f12204ad5cc7fe6579f69a4ea";
const AES_NONCE_HEX:      &str = "bc726bdd0e3f0d418778dd64";
const AES_AAD:            &[u8] = b"BCS-521-AAD-v1";
const AES_PLAINTEXT:      &[u8] = b"Bismillah ar-Rahman ar-Raheem -- BCS-521 test vector v1";
const AES_CIPHERTEXT_HEX: &str = "d3e95757a5c25b81321c316e75b9a745f988754980c3e15ce1b1152735cd31f1ed8d02a1c086a8f0dbb7134ec3a54be26b6f5fcacfb50d";
const AES_TAG_HEX:        &str = "47117440aacb8ffbea7f55fec371496e";

// ---- HKDF derivation constants ----
const HKDF_SALT: &[u8] = b"BCS-521-salt-v1";
const HKDF_INFO: &[u8] = b"BCS-521-ECDH-AES256GCM-v1";

// ---- EC layer — frozen from bcs521_test_vectors.json ----
const ALICE_SK_HEX:   &str = "0089e7ff496b03fe09966ba9a1708ffe827767b58712461c24b6b03f28471a7dbd8e9164e1fd572ede3dff91bdc7b5b858c577ed8f287fb8b1493c162822fbc438c0";
const BOB_PK_X_HEX:   &str = "008b316b8ae96a3a5d3fb5098561bc35a12c219c1bfc21d659b93c79bc42da01b74b7621d3d91eff89104783b7c26f761e94adc3e8674666e4212671d5e56c19b66b";
const BOB_PK_Y_HEX:   &str = "00423d6f2f7e849c0435ff557b8d9828a556f7c8115b5ac79d9abb4016882d05126e7a1305f8aa35dc12e32ae3a78ac86a33a70dfc97765102fbad580a66a4b51e5f";
const SHARED_X_HEX:   &str = "01c80dc97890b1009128050781ef29492c5cec4c27e5960637f444f4818f2cea26bcb6bf2e713fbbd4915c82af191a90c75d40693700c74082e8563b98f312b95574";
const K2_POINT_X_HEX: &str = "019518d9dd3937793f42014dbae55e892ef7590cd2433e2e319c8746e6d20a210200becef1f4ba82d7a5596f4d3795df1a8d82dbe5067077a803dfaf895dfb3e3d03";

// ---- Kahf-bound layer (Theorem 18) — frozen 2026-05-17 ----
const KAHF_DST_521_HEX:    &str = "ea23985a03b0d28f71fb091e7d15aaf791f5cbbfd1f1e73237f7e9c6b449bf35";
const KAHF_HKDF64_HEX:     &str = "05be03a508cdc3dcd94e9450a83b57e15075193bbb35ff20cdfeb76c046de0979b9b767deb699631db38a5ce9ea16e3ed859bdfc5d2401e0ec7c882457c1e006";
const KAHF_AES_KEY_HEX:    &str = "05be03a508cdc3dcd94e9450a83b57e15075193bbb35ff20cdfeb76c046de097";
const KAHF_NONCE_HEX:      &str = "9b9b767deb699631db38a5ce";
const KAHF_CIPHERTEXT_HEX: &str = "55df8c4d0bf71920583c63fda496d250f14d3f4c62f3a948af7039670ce0c4b68642bed5d0d23e45da6ff130e1ec1ba0b85ee93ca1b7f6";
const KAHF_TAG_HEX:        &str = "b528f9bb949488893df326c3c7e71638";

fn h2b(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i+2], 16).unwrap())
        .collect()
}

// =========================================================
// TEST 1: AES-256-GCM encryption — fully frozen
// =========================================================
#[test]
fn tv_aes256gcm_encrypt() {
    let key_bytes = h2b(AES_KEY_HEX);
    let key: &Key<Aes256Gcm> = key_bytes.as_slice().try_into().unwrap();
    let cipher = Aes256Gcm::new(key);
    let nonce_bytes = h2b(AES_NONCE_HEX);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let ct_tag = cipher
        .encrypt(nonce, Payload { msg: AES_PLAINTEXT, aad: AES_AAD })
        .expect("AES-256-GCM encrypt failed");

    let mut expected = h2b(AES_CIPHERTEXT_HEX);
    expected.extend_from_slice(&h2b(AES_TAG_HEX));

    assert_eq!(
        hex::encode(&ct_tag), hex::encode(&expected),
        "AES-256-GCM ciphertext+tag mismatch"
    );
}

// =========================================================
// TEST 2: AES-256-GCM decryption round-trip
// =========================================================
#[test]
fn tv_aes256gcm_decrypt() {
    let key_bytes = h2b(AES_KEY_HEX);
    let key: &Key<Aes256Gcm> = key_bytes.as_slice().try_into().unwrap();
    let cipher = Aes256Gcm::new(key);
    let nonce_bytes = h2b(AES_NONCE_HEX);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let mut ct_tag = h2b(AES_CIPHERTEXT_HEX);
    ct_tag.extend_from_slice(&h2b(AES_TAG_HEX));

    let plain = cipher
        .decrypt(nonce, Payload { msg: &ct_tag, aad: AES_AAD })
        .expect("AES-256-GCM decrypt failed");

    assert_eq!(plain, AES_PLAINTEXT);
}

// =========================================================
// TEST 3: Scalar-mul k=1 → G itself (always passes)
// =========================================================
// `G` and `kG` deliberately use uppercase to mirror the mathematical
// notation (G = generator, kG = k·G).  This is the standard convention
// in every ECC textbook and in our `bcs-521.md` spec; renaming would
// hurt cross-document readability for a $13/hr style win.
#[test]
#[allow(non_snake_case)]
fn tv_scalar_mul_k1_is_G() {
    use num_traits::One;
    let c = bcs521();
    let G = c.g.clone();
    let kG = c.scalar_mul(&BigUint::one(), &G);
    assert_eq!(kG, G);
}

// =========================================================
// TEST 4: Scalar-mul k=2 → known frozen x-coord
// =========================================================
#[test]
#[allow(non_snake_case)] // `kG` mirrors textbook notation, see TEST 3
fn tv_scalar_mul_k2_frozen() {
    let c = bcs521();
    let kG = c.scalar_mul(&BigUint::from(2u32), &c.g.clone());
    let got_x = match &kG {
        Point::Affine { x, .. } => hex::encode(x.to_bytes_be()),
        Point::Infinity => panic!("2*G should not be infinity"),
    };
    // Left-pad to 132 hex chars (66 bytes)
    let got_padded = format!("{:0>132}", got_x);
    assert_eq!(got_padded, K2_POINT_X_HEX,
        "2*G x-coord mismatch\n  got: {}\n  exp: {}", got_padded, K2_POINT_X_HEX);
}

// =========================================================
// TEST 5: HKDF-SHA-512 on known shared_x → AES key+nonce
// =========================================================
#[test]
fn tv_hkdf_sha512_from_shared_x() {
    let shared_x = h2b(SHARED_X_HEX);
    let out = hkdf_sha512_64(&shared_x, HKDF_SALT, HKDF_INFO);

    assert_eq!(hex::encode(&out[..32]), AES_KEY_HEX,
        "HKDF-SHA-512 first 32 bytes (AES key) mismatch");
    assert_eq!(hex::encode(&out[32..44]), AES_NONCE_HEX,
        "HKDF-SHA-512 bytes 32..44 (GCM nonce) mismatch");
}

// =========================================================
// TEST 6: Full ECDH → HKDF → AES-GCM pipeline
// =========================================================
#[test]
fn tv_full_pipeline_alice_to_ciphertext() {
    let curve = bcs521();

    let alice_sk = BigUint::from_bytes_be(&h2b(ALICE_SK_HEX));
    let bob_pk = Point::Affine {
        x: BigUint::from_bytes_be(&h2b(BOB_PK_X_HEX)),
        y: BigUint::from_bytes_be(&h2b(BOB_PK_Y_HEX)),
    };

    curve.validate_public_key(&bob_pk).expect("bob_pk invalid");
    let shared_x = curve.ecdh(&alice_sk, &bob_pk).expect("ECDH failed");
    assert_eq!(hex::encode(&shared_x), SHARED_X_HEX, "ECDH shared_x mismatch");

    let hkdf_out = hkdf_sha512_64(&shared_x, HKDF_SALT, HKDF_INFO);
    let aes_key: &Key<Aes256Gcm> = hkdf_out[..32].try_into().unwrap();
    let cipher = Aes256Gcm::new(aes_key);
    let nonce = Nonce::from_slice(&hkdf_out[32..44]);

    let ct_tag = cipher
        .encrypt(nonce, Payload { msg: AES_PLAINTEXT, aad: AES_AAD })
        .expect("AES-GCM encrypt failed");

    let mut expected = h2b(AES_CIPHERTEXT_HEX);
    expected.extend_from_slice(&h2b(AES_TAG_HEX));
    assert_eq!(hex::encode(&ct_tag), hex::encode(&expected),
        "Full pipeline ciphertext+tag mismatch");
}

// =========================================================
// TEST 7: Kahf DST hex matches Python reference
// =========================================================
#[test]
fn tv_kahf_dst_521_matches_python() {
    let dst = kahf_domain_separator("BCS-521-Kahf-v1");
    assert_eq!(hex::encode(dst), KAHF_DST_521_HEX, "Kahf DST hex mismatch");
}

// =========================================================
// TEST 8: Kahf-bound HKDF-SHA-512 matches Python reference
// =========================================================
#[test]
fn tv_kahf_hkdf_from_shared_x() {
    let shared_x = h2b(SHARED_X_HEX);
    let out = hkdf_sha512_64_kahf(&shared_x, HKDF_SALT, HKDF_INFO);
    assert_eq!(hex::encode(out), KAHF_HKDF64_HEX,
        "Kahf-bound HKDF-SHA-512 (64 B) mismatch");
    assert_eq!(hex::encode(&out[..32]), KAHF_AES_KEY_HEX);
    assert_eq!(hex::encode(&out[32..44]), KAHF_NONCE_HEX);
}

// =========================================================
// TEST 9: Kahf-bound full pipeline ECDH → HKDF-Kahf → AES-GCM
// =========================================================
#[test]
fn tv_kahf_full_pipeline() {
    let curve = bcs521();

    let alice_sk = BigUint::from_bytes_be(&h2b(ALICE_SK_HEX));
    let bob_pk = Point::Affine {
        x: BigUint::from_bytes_be(&h2b(BOB_PK_X_HEX)),
        y: BigUint::from_bytes_be(&h2b(BOB_PK_Y_HEX)),
    };

    curve.validate_public_key(&bob_pk).expect("bob_pk invalid");
    let shared_x = curve.ecdh(&alice_sk, &bob_pk).expect("ECDH failed");

    let hkdf_out = hkdf_sha512_64_kahf(&shared_x, HKDF_SALT, HKDF_INFO);
    let aes_key: &Key<Aes256Gcm> = hkdf_out[..32].try_into().unwrap();
    let cipher = Aes256Gcm::new(aes_key);
    let nonce = Nonce::from_slice(&hkdf_out[32..44]);

    let ct_tag = cipher
        .encrypt(nonce, Payload { msg: AES_PLAINTEXT, aad: AES_AAD })
        .expect("AES-GCM encrypt failed");

    let mut expected = h2b(KAHF_CIPHERTEXT_HEX);
    expected.extend_from_slice(&h2b(KAHF_TAG_HEX));
    assert_eq!(hex::encode(&ct_tag), hex::encode(&expected),
        "Kahf-bound full pipeline ciphertext+tag mismatch");
}

// =========================================================
// TEST 10: Kahf binding actually changes ciphertext
// =========================================================
#[test]
fn tv_kahf_differs_from_plain() {
    assert_ne!(KAHF_AES_KEY_HEX, AES_KEY_HEX,
        "Kahf AES key MUST differ from plain");
    assert_ne!(KAHF_CIPHERTEXT_HEX, AES_CIPHERTEXT_HEX,
        "Kahf ciphertext MUST differ from plain");
}
